testURL = http://coreopsdev.lubanzi.tech/
WAIT_TIME = 15
Screenshot_Path = src/test/resources/Screenshots/

#Login Credentials
Email = phumzilem@lubanzi.tech
Password = Buhle@001

#Dashboard test data
Dash_URL = http://coreopsdev.lubanzi.tech/Dashboard
Projects = 34
Employees = 16
TimesheetsSubmitted=15
LeaveRequests=10
Dash_WelcomeMsg = Welcome To Our Dashboard

#LeaveRequestList Test data
leaveBanner = Leave Request List
LeaveEmployees = Phumzile Motau,\
                 Naledi,\
                 Zinhle,\
                 Ndzalo,\
                 Zuziwe Maphumulo,\
                 Olwethu Mdutyulwa,\
                 Ndzalo Ngoveni,\
                 Trust Nkuna,\
                 Kamogelo Masha,\
                 Mpuru Naledi,\
                 Farmer Support,\
                 Dumisane Mbhele,\
                 Solomon Spencer,\
                 Zinhle,\
                 Gugu

LeaveTypes = Sick,\
             Annual,\
             Study,\
             Maternity
LeaveStatus= Approved,\
             Rejected,\
             Cancelled,\
             Pending,
EmployeeNameSearch = Dumisane Mbhele
LeaveTypeSearch=Annual
leaveStatusForAApprovedRequest = Approved
leaveStatusForARejectedRequest = Rejected
leaveCancellationResult = Cancelled

EditRequestHeader = Review Leave Request






